routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');



Auth::routes();



Route::resource('News','NewsController');
Route::resource('contact','ContactController');
Route::resource('cms/news','CmsNewsController');

app/BaseModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class BaseModel extends Model {
    protected $guarded = [];

    public function __get($key)
    {
        $magicGets = array_filter(get_class_methods($this), function ($method) {
            return Str::startsWith($method, '__get') && $method !== "__get";
        });
        foreach ($magicGets as $magicGet) {
            $res = $this->{$magicGet}($key);
            if ($res !== null) {
                return $res;
            }
        }

        return parent::__get($key);
    }
}

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Translation;
use App\Photo;

class News extends Model
{
    //

    protected $fillable = ['title','body','user_id','intro'];
    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function translation()
    {
        return $this->belongsTo('App\Translation');
    }
    public function photo(){
        return $this->belongsTo('App\Photo');
    }
}

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    //
    protected $uploads = '/img/';
    protected $fillable = ['file'];
    public function getFileAttribute($photo){
        return $this->uploads . $photo;
    }
}

app/Translation.php
<?php


namespace App;

class Translation extends BaseModel
{
    protected $casts = [
        'fields' => 'array'
    ];

    public function translatable()
    {
        return $this->morphTo();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\News;
class User extends BaseModel
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    public function news(){
        return $this->hasMany('App\News');
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CmsNewsController.php
<?php

namespace App\Http\Controllers;
use App\Translation;
use App\Http\Traits\Translatable;
use App\News;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;

class   CmsNewsController extends Controller
{
    use translatable;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $news = News::all();
        return view('cms/news.index',compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $user =User::pluck('name','id')->all();
        return view('cms.news.create',compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $input = $request->all();


        if($file = $request->file('photo_id')){
            $name = time() . $file->getClientOriginalName();
            $file->move('img',$name);
            $photo = Photo::create(['file'=>$name]);
            $input['photo_id'] = $photo->id;
        }
        News::create($input);

        return redirect('cms/news');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $new = News::findOrFail($id);
        $user =User::pluck('name','id')->all();
        return view('cms/news/edit',compact('new','user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id )
    {
        //
        $input = $request->all();
        $new = News::findOrFail($id);
        if($file = $request->file('photo_id')){
            $name = time().$file->getClientOriginalName();
            $file->move('images',$name);
            $photo= Photo::create(['file' =>$name]);
            $input['photo_id']= $photo->id;
        }


        $new->update($input);
        return redirect('/cms/news');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $news = News::findOrFail($id);
        unlink(public_path() . $news->photo->file);
        $news->delete();
        return redirect('cms.news.index');
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mail;

class ContactController extends Controller
{
    public function index(){
        //
        return view('contact');
    }
    public function store(Request $request){
        $this->validate($request,[
            'firstName'=>'required',
            'lastName'=>'required',
            'email'=>'required',
            'message'=>'required',
        ]);
        Mail::send('contact.mail',[
            'msg'=>$request->message
        ],function ($mail) use($request){
            $mail->from($request->email, $request->firstName);

            $mail->to('info@client.be')->subject('contact');
        });
        return redirect()->back()->with('message','thank you for contacting us');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('cms.news');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\News;
class NewsController extends Controller
{
    //
    public function index()
    {

        $news = News::all();
        $users = User::all();

        return view('news',compact('news','users'));
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        return view('news_detail', ['new' => News::findOrFail($id)]);
    }
}

resources/views/cms/news/create.blade.php
<x-cms>
    <div class="container">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Editing news item</h6>
            </div>
            <div class="card-body">
                {!! Form::open(['method'=>'POST','action'=>'CmsNewsController@store','files'=>true]) !!}
                <div class="form-group">
                    {!! Form::label('user_id','Author:') !!}
                    {!! Form::select('user_id',[''=>'Choose Author']+$user,null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('title','Title:') !!}
                    {!! Form::text('title',null,['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('intro','Intro:') !!}
                    {!! Form::textarea('intro',null,['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('body','Html:') !!}
                    {!! Form::textarea('body',null,['class'=>'form-control']) !!}
                </div>
{{--                <div class="form-group">--}}
{{--                    {!! Form::label('photo_id','Photo:') !!}--}}
{{--                    {!! Form::file('photo_id',null,['class'=>'form-control']) !!}--}}

{{--                </div>--}}


                <div class="form-group">
                    {!! Form::submit('Create news', ['class'=>'btn btn-success btn-block']) !!}
                </div>
                {!! Form::close() !!}
            </div>
        </div>

    </div>
</x-cms>

resources/views/cms/news/edit.blade.php
<x-cms>
    <div class="container">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Editing news item</h6>
            </div>
            <div class="card-body">
                {!! Form::model($new,['method'=>'PATCH','action'=>['CmsNewsController@update',$new->id],'files'=>true]) !!}

                <div class="form-group">
                    {!! Form::label('user_id','Author:') !!}
                    {!! Form::select('user_id',[''=>'Choose Author']+$user,null, ['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('title','Title:') !!}
                    {!! Form::text('title',null,['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('intro','Intro:') !!}
                    {!! Form::textarea('intro',null,['class'=>'form-control']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('body','Html:') !!}
                    {!! Form::textarea('body',null,['class'=>'form-control']) !!}
                </div>
                {{--                <div class="form-group">--}}
                {{--                    {!! Form::label('photo_id','Photo:') !!}--}}
                {{--                    {!! Form::file('photo_id',null,['class'=>'form-control']) !!}--}}

                {{--                </div>--}}


                <div class="form-group">
                    {!! Form::submit('Create news', ['class'=>'btn btn-success btn-block']) !!}
                </div>
                {!! Form::close() !!}
                {!! Form::open(['method'=>'DELETE','action'=>['CmsNewsController@destroy', $new->id]]) !!}
                <div class="form-group">
                    {!! Form::submit('Delete News',['class'=>'btn btn-danger btn-block ']) !!}
                </div>
                {!! Form::close() !!}
        </div>

    </div>
</x-cms>

resources/views/cms/news/index.blade.php
<x-cms>
    <div class="container-fluid">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">News</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Intro</th>
                            <th>Author</th>
                            <th>Created At</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Title</th>
                            <th>Intro</th>
                            <th>Author</th>
                            <th>Created At</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @if($news)
                            @foreach($news as $new)
                                <tr>

                                    <td>{{$new->title}}</td>
                                    <td>{{$new->body}}</td>
                                    <td><a href="{{route('news.edit',$new->id)}}">{{$new->user->name}}</a></td>
                                    <td>{{$new->created_at}}</td>
                                </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</x-cms>

resources/views/contact.blade.php
<x-layout>
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <h4 class="mb-3">Contact us</h4>
                <div class="row">
                <div class="col-md-6 mx-auto">
                    @if(Session::has('flash-message'))
                        <div class="alert alert-success">
                            {{Session::get('message')}}
                        </div>
                        @endif
                <form method="post" action="{{route('contact.store')}}">
                    {{csrf_field()}}

                    <div class="form-group">
                            <label for="firstName">First name*</label>
                            <input type="text" class="form-control " name="firstName" placeholder=""  required="">
                            <div class="invalid-feedback">
                                Valid first name is required.
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="lastName">Last name*</label>
                            <input type="text" class="form-control" name="lastName" placeholder=""  required="">
                            <div class="invalid-feedback">
                                Valid last name is required.
                            </div>
                        </div>


                    <div class="form-group">
                        <label for="email">Email*</label>
                        <input type="email" class="form-control" name="email" placeholder="" required="">
                        <div class="invalid-feedback">
                            Please enter a valid email address.
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="message">Message*</label>
                        <textarea name="message" cols="30" rows="10" class="form-control"></textarea>
                        <div class="invalid-feedback">
                            Valid messages is required.

                        </div>
                    </div>
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Send</button>
                </form>
    </div>
                </div>

            </div>
        </div>
    </div>
</x-layout>

resources/views/contact/mail.blade.php
{{$msg}}

resources/views/home.blade.php
<x-layout>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
                <div class="container">
                    <div class="carousel-caption text-left">
                        <h1>Example headline.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Another example headline.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
                <div class="container">
                    <div class="carousel-caption text-right">
                        <h1>One more for good measure.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
                <h2>Heading</h2>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
                <h2>Heading</h2>
                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5">
                <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7 order-md-2">
                <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5 order-md-1">
                <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5">
                <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
            </div>
        </div>

        <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->
</x-layout>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/news.blade.php
<x-layout>
    <div class="container mt-5">
        <div class="row">
            @if($news)
            @foreach ($news as $new)
                <div class="col-md-4">
                    <a class="card mb-4 shadow-sm text-decoration-none" href="#">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                             xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false"
                             role="img" aria-label="Placeholder: Thumbnail"><title>{{$new->title}}</title>
                            <rect width="100%" height="100%" fill="#55595c"></rect>
                            <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                        </svg>{route('profile', ['id' => 1]
                        <div class="card-body text-dark">
                            <h3><a href="{{route('news_detail', ['id' => $new->id])}}">{{$new->title}}</a></h3>
                            <p class="card-text">{{$new->intro}}</p>
                            <div class="text-right">
                                <small class="text-muted">By {{$new->user->name}}</small>
                            </div>
                        </div>
                    </a>
                </div>
            @endforeach
                @endif
        </div>
    </div>
</x-layout>

resources/views/news_detail.blade.php
<x-layout>
    <div class="container mt-5">
        @if($new)
        <h2>{{$new->title}}</h2>
        <p>{{$new->body}}</p>
            @endif
    </div>
</x-layout>